#The first packages the library as a .ZIP file as would be uploaded to PyPI
#The second looks for all .ZIP files in the build (which here will just be the package we created from the first line)
#and pipes the filenames through to pip install installing the packages as would an end-user

#This way, every time we check code in to GitHub we can ensure that it:

#The packaging configuration is correct and generates a sensible package
#The packaging configuration has all the prerequisites listed correctly and can be pulled down from PyPI
#The packaged and installed library works
#From: http://pablissimo.com/381/get-travis-ci-to-do-your-python-packaging-tests-for-you

language: python

dist: trusty

python:
  - "2.7"
before_install:
 - pip install -U nose-exclude setuptools
 - sudo apt-get update -qq
 - sudo apt-get install coinor-cbc
 - sudo apt-get install -qq python-dev libboost-python-dev libboost-serialization-dev
# command to package and install
install:
 - python setup.py sdist --formats=zip -k
 - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
# command to run tests
script: nosetests --exclude-dir=Fred2/test/external Fred2
